const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {qualificationFixture}=require('../scripts/economics/qualification-fixture.cjs');
const {checkAdmission}=require('../scripts/economics/admission.cjs');
const {buildCalibration}=require('../scripts/economics/calibration.cjs');
const {lifecycle}=require('../scripts/economics/lifecycle.cjs');
function changeReport(x,fn){const r=JSON.parse(x.evidenceReport);fn(r);x.evidenceReport=JSON.stringify(r);x.envelope.payload.evidence.reportSha256=crypto.createHash('sha256').update(x.evidenceReport).digest('hex');x.resign();}
describe('Calibrated admission and funded retainer accounting',()=>{
 it('requires the signed report bytes and labels simulated evidence accurately',()=>{const x=qualificationFixture(),r=checkAdmission(x);assert.equal(r.schemaVersion,4);assert.equal(r.calibration.measurementKind,'simulated');assert.equal(r.calibration.evaluationSamples,100);assert.throws(()=>checkAdmission({...x,evidenceReport:undefined}),/CALIBRATION_REPORT_REQUIRED/);assert.throws(()=>checkAdmission({...x,evidenceReport:x.evidenceReport+' '}),/REPORT_HASH/);});
 it('checks employer retainer costs and reviewer receipts on early acceptance',()=>{const x=qualificationFixture();for(const id of Object.keys(x.model.cases.find(r=>r.id==='acceptance').ballots))x.model.cases.find(r=>r.id==='acceptance').ballots[id]='absent';const r=lifecycle(x.model).cases.find(x=>x.id==='acceptance');assert.equal(r.netUSDC.employer,'966');assert.equal(r.netUSDC.reviewer1,'4');});
 it('does not count an unavailable retainer as reviewer cash',()=>{const x=qualificationFixture();const r=lifecycle(x.model).cases.find(x=>x.id==='unpaid');assert.equal(r.netUSDC.employer,'-1034');assert.equal(r.netUSDC.reviewer1,'-154');});
 it('rejects unsupported source kinds and changed deployment scopes',()=>{for(const mutate of [r=>r.measurementKind='observed',r=>r.environmentSha256='0'.repeat(64),r=>r.jobClass='other',r=>r.economicScopeSha256='0'.repeat(64)]){const x=qualificationFixture();changeReport(x,mutate);assert.throws(()=>checkAdmission(x),/CALIBRATION/);}});
 it('rejects optimistic zero-weight stresses despite a fresh signature',()=>{const x=qualificationFixture();x.model.cases[0].weightPpm+=10000;x.model.cases.at(-1).weightPpm=0;x.resign();assert.throws(()=>checkAdmission(x),/ZERO_WEIGHT_STRESS/);});
 it('rejects frequency drift in either partition',()=>{for(const partition of ['calibration','evaluation']){const x=qualificationFixture();changeReport(x,r=>{r.cases.success[partition].count-=10;r.cases['buyer-win'][partition].count+=10;});assert.throws(()=>checkAdmission(x),/PROBABILITY_DRIFT/);}});
 it('rejects cost understatement and employer value overstatement',()=>{for(const mutate of [r=>r.cases.success.evaluation.maximumCostsUSDC.reviewer1='5',r=>r.cases.success.evaluation.minimumEmployerValueUSDC='1999']){const x=qualificationFixture();changeReport(x,mutate);assert.throws(()=>checkAdmission(x),/UNDERSTATEMENT|OVERSTATEMENT/);}});
 it('rejects held-out loss rates and realized margins outside policy',()=>{for(const mutate of [r=>r.cases.success.evaluation.losses.reviewer1=50,r=>r.cases.success.evaluation.netSumMicro.reviewer1='-99999999999']){const x=qualificationFixture();changeReport(x,mutate);assert.throws(()=>checkAdmission(x),/REALIZED_MARGIN|REALIZED_LOSS_RATE/);}});
 it('rejects duplicate observations, group leakage and financial imbalance at ingestion',()=>{for(const mutate of [d=>d.records[1].id=d.records[0].id,d=>d.records.at(-1).group=d.records[0].group,d=>d.records[0].receiptsUSDC={...d.records[0].receiptsUSDC,agent:'99999'}]){const x=qualificationFixture();mutate(x.dataset);assert.throws(()=>buildCalibration(x.model,x.dataset),/DUPLICATE|LEAKAGE|ACCOUNTING/);}});
 it('rejects group leakage even inside an issuer-signed report',()=>{const x=qualificationFixture();changeReport(x,r=>r.groups.evaluation=[r.groups.calibration[0]]);assert.throws(()=>checkAdmission(x),/GROUP_LEAKAGE/);});
 it('binds measurement time and exact evaluation sample count',()=>{for(const mutate of [p=>p.evidence.sampleCount=101,p=>p.evidence.measuredAt--]){const x=qualificationFixture();mutate(x.envelope.payload);x.resign();assert.throws(()=>checkAdmission(x),/BINDING/);}});
 it('keeps reviewer commitments fixed under the calibrated schema',()=>{const x=qualificationFixture({role:'reviewer'});assert.equal(checkAdmission(x).commitment.decision,'approve');x.observed.commitment={...x.observed.commitment,decision:'reject'};assert.throws(()=>checkAdmission(x),/COMMITMENT_CHANGED/);});
 it('prevents treating review funding as free external revenue',()=>{const x=qualificationFixture();delete x.model.reviewRetainers.reviewer1;x.resign();assert.throws(()=>checkAdmission(x));});
});
