const assert=require('node:assert/strict');
describe('Bounded qualification scheduling',()=>{
 let Service;before(async()=>{({QualificationService:Service}=await import('../scripts/economics/qualification-service.mjs'));});
 const deferred=()=>{let resolve;const promise=new Promise(r=>{resolve=r;});return {resolve,promise};};
 it('reserves execution capacity for recovery while intake is busy',async()=>{const s=new Service({maxConcurrent:2}),d=deferred(),order=[];const a=s.run('a',async()=>{order.push('a');await d.promise;});const b=s.run('b',()=>order.push('b'));const r=s.run('recover',()=>order.push('recovery'),{priority:'recovery'});await r;assert.deepEqual(order,['a','recovery']);d.resolve();await Promise.all([a,b]);s.close();});
 it('bounds queues, rejects duplicates and never serves cached authority',async()=>{const s=new Service({maxConcurrent:2,maxQueued:2}),d=deferred();const a=s.run('a',()=>d.promise);const b=s.run('b',()=>1);await assert.rejects(s.run('c',()=>2),/QUEUE_FULL/);await assert.rejects(s.run('a',()=>2),/ALREADY_RUNNING/);d.resolve();await Promise.all([a,b]);await new Promise(setImmediate);let calls=0;await s.run('a',()=>++calls);await new Promise(setImmediate);await s.run('a',()=>++calls);assert.equal(calls,2);s.close();});
 it('rejects expired requests before executing their work',async()=>{const s=new Service();let called=false;await assert.rejects(s.run('old',()=>{called=true;},{deadlineMs:Date.now()-1}),/DEADLINE/);assert.equal(called,false);s.close();});
 it('retains timed-out running work in the concurrency budget until it actually stops',async()=>{const s=new Service({maxConcurrent:2,maxTaskMs:15}),d=deferred();await assert.rejects(s.run('a',()=>d.promise),/TASK_DEADLINE/);assert.equal(s.snapshot().running,1);await assert.rejects(s.run('a',()=>1),/ALREADY_RUNNING/);const recovery=await s.run('r',()=>7,{priority:'recovery'});assert.equal(recovery,7);d.resolve();await new Promise(setImmediate);assert.equal(s.snapshot().running,0);s.close();});
 it('does not execute expired queued work',async()=>{const s=new Service({maxConcurrent:2,maxQueueMs:10,maxTaskMs:1000}),d=deferred();const a=s.run('a',()=>d.promise);let called=false;await assert.rejects(s.run('b',()=>{called=true;}),/QUEUE_DEADLINE/);assert.equal(called,false);d.resolve();await a;s.close();});
 it('rejects shutdown results and does not return late authority',async()=>{const s=new Service(),d=deferred();const pending=s.run('a',()=>d.promise);s.close();d.resolve(1);await assert.rejects(pending,/STOPPED/);await assert.rejects(s.run('b',()=>2),/STOPPED/);});
 it('records failures and latency separately from overload rejection',async()=>{const s=new Service();await assert.rejects(s.run('a',()=>{throw Error('bad proof');}),/bad proof/);await new Promise(setImmediate);assert.equal(s.snapshot().failed,1);assert.equal(s.snapshot().completed,0);assert.equal(s.snapshot().retainedLatencySamples,1);s.close();});
});
