const assert = require('node:assert/strict');
const { MerkleTree } = require('merkletreejs');
const keccak256 = require('keccak256');
const { BN, expectRevert, time } = require('../scripts/test-helpers.cjs');
const { buildInitConfig, deployActive } = require('./helpers/deploy');
const { rootNode } = require('./helpers/ens');
const { fundAgents } = require('./helpers/bonds');
const Manager = artifacts.require('AGIJobManager');
const Escrow = artifacts.require('AGIReviewEscrow');
const Token = artifacts.require('FailingERC20');
const ENS = artifacts.require('MockENS');
const Wrapper = artifacts.require('MockNameWrapper');
const cash = n => new BN(String(n)).mul(new BN('1000000'));
contract('Funded review retainers', accounts => {
  const [owner, employer, agent, reviewer, reviewer2, outsider] = accounts;
  let token, manager, escrow, id, expiry;
  const delivery='ipfs://exact-delivery';
  const deliveryHash=web3.utils.keccak256(delivery);
  beforeEach(async()=>{
    token=await Token.new();const ens=await ENS.new(),wrapper=await Wrapper.new();
    const tree=new MerkleTree([Buffer.from(web3.utils.soliditySha3({type:'address',value:agent}).slice(2),'hex')],keccak256,{sortPairs:true});
    manager=await deployActive(Manager,...buildInitConfig(token.address,'ipfs://base',ens.address,wrapper.address,rootNode('club'),rootNode('agent'),rootNode('club'),rootNode('agent'),'0x'+'00'.repeat(32),tree.getHexRoot()),{from:owner});
    await token.mint(employer,cash(10000));await token.approve(manager.address,cash(1000),{from:employer});
    await manager.createJob('ipfs://spec',cash(1000),5000,'details',{from:employer});
    await fundAgents(token,manager,[agent],owner);await manager.applyForJob(0,'agent',tree.getHexProof(tree.getLeaves()[0]),{from:agent});
    await manager.requestJobCompletion(0,delivery,{from:agent});
    escrow=await Escrow.new(manager.address);await token.approve(escrow.address,cash(100),{from:employer});
    expiry=Number((await global.__contractTestRuntime.rpc('eth_getBlockByNumber',['latest',false])).timestamp)+600;id=await escrow.assignmentId(0,reviewer);
  });
  const fund=()=>escrow.fundReview(0,reviewer,deliveryHash,cash(10),expiry,{from:employer});
  it('backs the named retainer without changing manager escrow or payout terms',async()=>{await fund();assert.equal(String(await escrow.totalLiability()),String(cash(10)));assert.equal(String(await token.balanceOf(escrow.address)),String(cash(10)));assert.equal(String(await manager.lockedEscrow()),String(cash(1000)));assert.equal(String(await escrow.credits(reviewer)),'0');});
  it('earns an irrevocable retainer and permits anyone to pay only its beneficiary',async()=>{await fund();await escrow.activateReview(id,{from:reviewer});await escrow.withdrawCredit(reviewer,{from:outsider});assert.equal(String(await token.balanceOf(reviewer)),String(cash(10)));assert.equal(String(await escrow.totalLiability()),'0');assert.equal(String((await escrow.assignments(id)).state),'2');});
  it('preserves earned payment when the employer accepts before any vote',async()=>{await fund();await escrow.activateReview(id,{from:reviewer});await manager.acceptJob(0,{from:employer});await escrow.withdrawCredit(reviewer,{from:outsider});assert.equal(String(await token.balanceOf(reviewer)),String(cash(10)));assert.equal(String((await manager.getJobValidation(0)).validatorApprovals),'0');});
  it('blocks activation when buyer acceptance wins the race and permits refund',async()=>{await fund();await manager.acceptJob(0,{from:employer});await expectRevert.unspecified(escrow.activateReview(id,{from:reviewer}));await escrow.refundReview(id,{from:employer});assert.equal(String(await escrow.credits(employer)),String(cash(10)));});
  it('blocks employer clawback after activation, even after the start deadline',async()=>{await fund();await escrow.activateReview(id,{from:reviewer});await time.increase(601);await expectRevert.unspecified(escrow.refundReview(id,{from:employer}));await expectRevert.unspecified(escrow.refundReview(id,{from:outsider}));assert.equal(String(await escrow.credits(reviewer)),String(cash(10)));});
  it('prevents duplicate funding, duplicate activation and double withdrawal',async()=>{await fund();await expectRevert.unspecified(fund());await escrow.activateReview(id,{from:reviewer});await expectRevert.unspecified(escrow.activateReview(id,{from:reviewer}));await escrow.withdrawCredit(reviewer);await expectRevert.unspecified(escrow.withdrawCredit(reviewer));});
  it('requires employer funding and activation by the exact assigned reviewer',async()=>{await expectRevert.unspecified(escrow.fundReview(0,reviewer,deliveryHash,cash(10),expiry,{from:outsider}));await fund();await expectRevert.unspecified(escrow.activateReview(id,{from:outsider}));await expectRevert.unspecified(escrow.activateReview(id,{from:employer}));});
  it('rejects self-review assignments, zero fees and wrong delivery commitments',async()=>{for(const who of [employer,agent,'0x'+'0'.repeat(40),escrow.address,manager.address,token.address])await expectRevert.unspecified(escrow.fundReview(0,who,deliveryHash,cash(10),expiry,{from:employer}));await expectRevert.unspecified(escrow.fundReview(0,reviewer,deliveryHash,0,expiry,{from:employer}));await expectRevert.unspecified(escrow.fundReview(0,reviewer,web3.utils.keccak256('different'),cash(10),expiry,{from:employer}));});
  it('rejects expired and excessively long assignments',async()=>{const now=Number((await global.__contractTestRuntime.rpc('eth_getBlockByNumber',['latest',false])).timestamp);for(const until of [0,now,now+31*86400])await expectRevert.unspecified(escrow.fundReview(0,reviewer,deliveryHash,cash(10),until,{from:employer}));});
  it('allows bounded expiry recovery but never activates an expired assignment',async()=>{await fund();await expectRevert.unspecified(escrow.refundReview(id,{from:outsider}));await time.increase(601);await expectRevert.unspecified(escrow.activateReview(id,{from:reviewer}));await escrow.refundReview(id,{from:outsider});await escrow.withdrawCredit(employer,{from:outsider});assert.equal(String(await escrow.totalLiability()),'0');});
  it('keeps cancellation final and prevents assignment replay',async()=>{await fund();await escrow.refundReview(id,{from:employer});await expectRevert.unspecified(escrow.activateReview(id,{from:reviewer}));await expectRevert.unspecified(fund());});
  it('preserves credits and liability when USDC payment fails',async()=>{await fund();await escrow.activateReview(id,{from:reviewer});await token.setFailTransfers(true);await expectRevert.unspecified(escrow.withdrawCredit(reviewer));assert.equal(String(await escrow.credits(reviewer)),String(cash(10)));assert.equal(String(await escrow.totalLiability()),String(cash(10)));await token.setFailTransfers(false);await escrow.withdrawCredit(reviewer);assert.equal(String(await escrow.credits(reviewer)),'0');});
  it('rolls back assignment and liability when funding fails',async()=>{await token.setFailTransferFroms(true);await expectRevert.unspecified(fund());assert.equal(String((await escrow.assignments(id)).state),'0');assert.equal(String(await escrow.totalLiability()),'0');});
  it('keeps independent assignments fully backed through mixed payment and refund',async()=>{await fund();await escrow.fundReview(0,reviewer2,deliveryHash,cash(12),expiry,{from:employer});await escrow.activateReview(id,{from:reviewer});await escrow.refundReview(await escrow.assignmentId(0,reviewer2),{from:employer});assert.equal(String(await escrow.totalLiability()),String(cash(22)));await escrow.withdrawCredit(reviewer);await escrow.withdrawCredit(employer);assert.equal(String(await token.balanceOf(escrow.address)),'0');});
  it('domain-separates assignments by deployed escrow',async()=>{const other=await Escrow.new(manager.address);assert.notEqual(id,await other.assignmentId(0,reviewer));});
});
