const assert=require('node:assert/strict');
const {reserveReviews}=require('../scripts/economics/review-reservation.cjs');
const {evaluatePilot}=require('../scripts/economics/pilot-evaluation.cjs');
const plan=()=>({schema:'agi-review-reservation/v1',measurementKind:'synthetic',now:100,terms:{minimumReviewers:3,challengeSeconds:10,reserveSeconds:10,requireDistinctFailureDomains:true},reviewers:[0,1,2].map(i=>({id:'node'+i,controller:'owner'+i,credential:'key'+i,failureDomain:'provider'+i,availableAt:100,reservations:[]})),jobs:[{id:'A',workReadyAt:100,deadline:170,reviewSeconds:30,requiredReviewers:3},{id:'B',workReadyAt:100,deadline:170,reviewSeconds:30,requiredReviewers:3}]});
const pilot=()=>({schema:'agi-pilot-evaluation/v1',measurementKind:'synthetic',cohort:'reference',counts:{offered:100,admitted:10,useful:9,humanSeconds:600,agentEngagements:10,agentLosses:1,reviewerEngagements:100,reviewerLosses:2,incorrectPaid:0,settlementsAudited:10,settlementRuleDefects:0,independentlyScoredReviews:100,reviewJudgmentErrors:0},thresholds:{minimumUsefulRateExclusive:.8,maximumHumanMinutesExclusive:15,maximumAgentLossRate:.25,maximumReviewerLossRate:.25,maximumJudgmentErrorUpper95:.05,minimumAuditedSettlements:10,minimumScoredReviews:100}});
describe('Independent review reservation planning',function(){
 it('schedules three independent Nodes without double booking and without mutating input',()=>{const p=plan(),before=JSON.stringify(p),r=reserveReviews(p);assert.equal(r.admitted,1);assert.equal(r.outcomes[1].reason,'REVIEW_DEADLINE');assert.equal(r.outcomes[0].reviewFinish,130);assert.equal(JSON.stringify(p),before);});
 it('uses later available slots and rejects a deadline behind booked time',()=>{const p=plan();p.jobs=p.jobs.slice(0,1);p.reviewers[1].reservations=[{jobId:'old',start:100,finish:150}];p.jobs[0].deadline=205;const r=reserveReviews(p);assert.equal(r.admitted,1);assert.equal(r.outcomes[0].reviewFinish,180);p.jobs[0].deadline=179;assert.equal(reserveReviews(p).outcomes[0].reason,'REVIEW_DEADLINE');});
 it('does not reserve partial reviewer time after rejection',()=>{const p=plan();p.jobs[0].deadline=140;p.jobs[1].deadline=180;const r=reserveReviews(p);assert.deepEqual(r.outcomes.map(x=>x.admitted),[false,true]);assert.equal(r.outcomes[1].reviewFinish,130);});
 it('rejects common control and overlapping existing bookings',()=>{const p=plan();p.reviewers[1].controller='owner0';assert.throws(()=>reserveReviews(p),/INDEPENDENT_CONTROL/);p.reviewers[1].controller='owner1';p.reviewers[1].reservations=[{jobId:'old',start:100,finish:130},{jobId:'other',start:120,finish:140}];assert.throws(()=>reserveReviews(p),/OVERLAP/);});
 it('refuses replayed job IDs already present in reviewer bookings',()=>{const p=plan();p.reviewers[0].reservations=[{jobId:'A',start:100,finish:130}];assert.throws(()=>reserveReviews(p),/EXISTING_JOB_ID/);});
 it('requires distinct declared failure domains when configured',()=>{const p=plan();p.reviewers[1].failureDomain='provider0';assert.equal(reserveReviews(p).outcomes[0].reason,'CORRELATED_FAILURE_DOMAINS');p.terms.requireDistinctFailureDomains=false;assert.equal(reserveReviews(p).outcomes[0].correlationWarning,true);});
 it('rejects absent quorum and incomplete review',()=>{const p=plan();p.reviewers.pop();assert.equal(reserveReviews(p).outcomes[0].reason,'INSUFFICIENT_REVIEWERS');p.reviewers.push({id:'node2',controller:'owner2',credential:'key2',failureDomain:'provider2',availableAt:100,reservations:[]});p.jobs[0].deadline=149;assert.equal(reserveReviews(p).outcomes[0].reason,'REVIEW_DEADLINE');});
});
describe('Pilot outcomes and missing evidence',function(){
 it('passes a fully declared synthetic target without authorizing intake',()=>{const r=evaluatePilot(pilot());assert.equal(r.allTargetsMet,true);assert.equal(r.measurementKind,'synthetic');assert.equal(r.authorization,'NONE');});
 it('fails each strict threshold and separately reports judgment error',()=>{const p=pilot();p.counts.useful=8;assert.equal(evaluatePilot(p).checks.usefulRate,false);p.counts.useful=9;p.counts.humanSeconds=8100;assert.equal(evaluatePilot(p).checks.humanTime,false);p.counts.humanSeconds=600;p.counts.agentLosses=3;assert.equal(evaluatePilot(p).checks.agentLosses,false);p.counts.agentLosses=1;p.counts.reviewerLosses=26;assert.equal(evaluatePilot(p).checks.reviewerLosses,false);p.counts.reviewerLosses=2;p.counts.reviewJudgmentErrors=2;assert.equal(evaluatePilot(p).checks.judgmentQuality,false);});
 it('fails closed when settlement audit or independent ground truth is absent',()=>{const p=pilot();p.counts.settlementsAudited=0;p.counts.independentlyScoredReviews=0;const r=evaluatePilot(p);assert.equal(r.allTargetsMet,false);assert.deepEqual(r.missingEvidence,['SETTLEMENT_AUDIT','INDEPENDENT_REVIEW_GROUND_TRUTH']);});
 it('separates incorrect payment, judgment error and settlement-rule defect',()=>{const p=pilot();p.counts.incorrectPaid=1;let r=evaluatePilot(p);assert.equal(r.metrics.incorrectPaid,1);assert.equal(r.checks.settlementRules,true);p.counts.settlementRuleDefects=1;r=evaluatePilot(p);assert.equal(r.checks.settlementRules,false);});
 it('rejects impossible counts and non-finite thresholds',()=>{const p=pilot();p.counts.useful=11;assert.throws(()=>evaluatePilot(p),/COUNT_RELATION/);p.counts.useful=9;p.thresholds.maximumJudgmentErrorUpper95=NaN;assert.throws(()=>evaluatePilot(p),/THRESHOLDS/);});
});
