const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {canonical,digest,checkAdmission}=require('../scripts/economics/admission.cjs');
const sample=require('../scripts/economics/lifecycle-example.json');
const addr=n=>'0x'+n.toString(16).padStart(40,'0');
const now=Math.floor(Date.now()/1000),clone=x=>JSON.parse(JSON.stringify(x));
function fixture() {
 const keys=crypto.generateKeyPairSync('ed25519'),input=clone(sample);
 const policy={schemaVersion:3,epoch:'funding-allocation-1',chainId:1,manager:addr(99),wallet:addr(1),role:'employer',trustedKeys:{issuer:keys.publicKey.export({type:'spki',format:'pem'})},classes:['catalog'],maxPacketAgeSeconds:600,maxEvidenceAgeSeconds:86400,minimumSamples:100,minimumHorizonDays:180,limits:{employer:{minimumExpectedNetUSDC:'100',maximumScenarioLossUSDC:'1100'},agent:{minimumExpectedNetUSDC:'100',maximumScenarioLossUSDC:'100'},reviewer:{minimumExpectedNetUSDC:'10',maximumScenarioLossUSDC:'160'}},maxOpenExposureUSDC:'5000',maxEpochCostUSDC:'100',maxOpenJobs:3,maxGasWeiPerJob:'1000000000000000',capacity:{allocationId:'dedicated-allocation',agentSlots:3,reviewerSlots:9,providerUnits:100}};
 const payload={schemaVersion:3,policyDigest:digest(policy),offerId:digest('offer'),participantId:'employer',jobClass:'catalog',issuedAt:now-10,expiresAt:now+500,specURI:'ipfs://fixture',specSha256:digest('spec'),evidence:{reportSha256:digest('report'),measuredAt:now-100,sampleCount:100,qualification:'qualified',costsIncludeFailuresAndOverhead:true},identities:Object.fromEntries(input.participants.map((p,i)=>[p.id,{wallet:addr(i+1),controllerId:digest('independent-'+i)}])),lifecycle:input,gasBudgetWei:'1000000000000000',ethPriceCeilingUSDC:'4000',commitment:{action:'createJob',durationSeconds:'100',details:'public task'},capacity:{allocationId:'dedicated-allocation',leaseId:digest('lease'),expiresAt:now+600,agentSlots:1,reviewerSlots:3,providerUnits:20},valueEvidence:{baselineSha256:digest('baseline'),outcomesSha256:digest('outcomes'),measurementKind:'observed',sampleCount:100}};
 const envelope={keyId:'issuer',payload,signature:''},observed={chainId:1,manager:policy.manager,wallet:policy.wallet,offerId:payload.offerId,specURI:payload.specURI,specSha256:payload.specSha256,terms:clone(input.terms),observedAt:now,commitment:clone(payload.commitment)};
 const resign=()=>{payload.policyDigest=digest(policy);envelope.signature=crypto.sign(null,Buffer.from(canonical(payload)),keys.privateKey).toString('base64');};resign();
 return {policy,envelope,observed,portfolio:{openExposureUSDC:'0',epochCostUSDC:'0',openJobs:0,capacity:{agentSlots:0,reviewerSlots:0,providerUnits:0}},now,resign};
}
describe('Pre-funding economic qualification',()=>{
 it('qualifies employer capital before a job ID exists, without granting transaction authority',()=>{const r=checkAdmission(fixture());assert.equal(r.schemaVersion,3);assert.equal(r.reserveExposureUSDC,'1010');assert.equal(r.jobId,undefined);assert.match(r.authorization,/^NONE/);});
 it('rejects an unqualified employer even when agent and reviewer economics pass',()=>{const x=fixture();for(const c of x.envelope.payload.lifecycle.cases)c.employerValueUSDC='0';x.resign();assert.throws(()=>checkAdmission(x),/ECONOMIC_LIMITS/);});
 it('checks every participating reviewer separately',()=>{const x=fixture();for(const c of x.envelope.payload.lifecycle.cases)c.costsUSDC.reviewer1='100';x.resign();assert.throws(()=>checkAdmission(x),/ECONOMIC_LIMITS/);});
 it('binds exact offer, duration, details and current posting-time economic terms',()=>{for(const mutate of [x=>x.observed.offerId=digest('other'),x=>x.observed.commitment.durationSeconds='101',x=>x.observed.commitment.details='changed',x=>x.observed.terms.rewardPercentage=9]){const x=fixture();mutate(x);assert.throws(()=>checkAdmission(x));}});
 it('requires observed value baseline, outcome hashes and minimum samples',()=>{for(const mutate of [v=>v.measurementKind='forecast',v=>v.baselineSha256='',v=>v.outcomesSha256='',v=>v.sampleCount=99]){const x=fixture();mutate(x.envelope.payload.valueEvidence);x.resign();assert.throws(()=>checkAdmission(x));}});
 it('cannot reuse worker policy or downgrade funding to legacy schema',()=>{for(const mutate of [x=>x.policy.role='agent',x=>x.envelope.payload.schemaVersion=1,x=>x.envelope.payload.commitment.action='apply']){const x=fixture();mutate(x);x.resign();assert.throws(()=>checkAdmission(x));}});
 it('separates capital, costs, job count and three capacity limits',()=>{for(const mutate of [p=>p.openExposureUSDC='3991',p=>p.epochCostUSDC='91',p=>p.openJobs=3,p=>p.capacity.agentSlots=3,p=>p.capacity.reviewerSlots=7,p=>p.capacity.providerUnits=81]){const x=fixture();mutate(x.portfolio);assert.throws(()=>checkAdmission(x));}});
 it('requires a scoped capacity lease lasting through the packet',()=>{for(const mutate of [c=>c.allocationId='other',c=>c.leaseId='',c=>c.expiresAt=now+499,c=>c.agentSlots=0,c=>c.providerUnits=101,c=>c.reviewerSlots=1]){const x=fixture();mutate(x.envelope.payload.capacity);x.resign();assert.throws(()=>checkAdmission(x));}});
 it('rejects malformed funding inputs and unknown fields',()=>{for(const mutate of [x=>x.envelope.payload.offerId='0',x=>x.envelope.payload.commitment.durationSeconds='0',x=>x.envelope.payload.commitment.durationSeconds='01',x=>x.envelope.payload.commitment.extra=true,x=>x.portfolio.capacity.providerUnits=-1]){const x=fixture();mutate(x);x.resign();assert.throws(()=>checkAdmission(x));}});
 it('keeps packet bytes immutable and detaches returned capacity',()=>{const x=fixture(),before=canonical(x.envelope),r=checkAdmission(x);r.capacity.agentSlots=100;assert.equal(canonical(x.envelope),before);});
});
module.exports={fixture};
