export const agiJobManagerAbi = [
  { type: 'function', name: 'owner', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'paused', stateMutability: 'view', inputs: [], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'settlementPaused', stateMutability: 'view', inputs: [], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'nextJobId', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'moderators', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'completionReviewPeriod', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'disputeReviewPeriod', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'challengePeriodAfterApproval', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'requiredValidatorApprovals', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'requiredValidatorDisapprovals', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'voteQuorum', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getJobCore', stateMutability: 'view', inputs: [{ type: 'uint256' }], outputs: [{ type: 'tuple', components: [
    { name: 'employer', type: 'address' },
    { name: 'assignedAgent', type: 'address' },
    { name: 'payout', type: 'uint256' },
    { name: 'duration', type: 'uint256' },
    { name: 'assignedAt', type: 'uint256' },
    { name: 'completed', type: 'bool' },
    { name: 'disputed', type: 'bool' },
    { name: 'expired', type: 'bool' },
    { name: 'agentPayoutPct', type: 'uint8' }
  ] }] },
  { type: 'function', name: 'getJobValidation', stateMutability: 'view', inputs: [{ type: 'uint256' }], outputs: [{ type: 'tuple', components: [
    { name: 'completionRequested', type: 'bool' },
    { name: 'approvals', type: 'uint256' },
    { name: 'disapprovals', type: 'uint256' },
    { name: 'completionRequestedAt', type: 'uint256' },
    { name: 'disputedAt', type: 'uint256' }
  ] }] },
  { type: 'function', name: 'getJobSpecURI', stateMutability: 'view', inputs: [{ type: 'uint256' }], outputs: [{ type: 'string' }] },
  { type: 'function', name: 'getJobCompletionURI', stateMutability: 'view', inputs: [{ type: 'uint256' }], outputs: [{ type: 'string' }] },
  { type: 'function', name: 'tokenURI', stateMutability: 'view', inputs: [{ type: 'uint256' }], outputs: [{ type: 'string' }] },
  { type: 'function', name: 'cancelJob', stateMutability: 'nonpayable', inputs: [{ type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'applyForJob', stateMutability: 'nonpayable', inputs: [{ type: 'uint256' }, { type: 'bytes32[]' }], outputs: [] },
  { type: 'function', name: 'requestCompletion', stateMutability: 'nonpayable', inputs: [{ type: 'uint256' }, { type: 'string' }], outputs: [] },
  { type: 'function', name: 'disputeJob', stateMutability: 'nonpayable', inputs: [{ type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'finalizeJob', stateMutability: 'nonpayable', inputs: [{ type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'pause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'unpause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'setSettlementPaused', stateMutability: 'nonpayable', inputs: [{ type: 'bool' }], outputs: [] },
  { type: 'event', name: 'JobCreated', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'JobApplied', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'JobCompletionRequested', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'JobValidated', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'JobDisapproved', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'JobDisputed', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'DisputeResolvedWithCode', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'JobCompleted', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'JobCancelled', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'JobExpired', anonymous: false, inputs: [{ indexed: true, name: 'jobId', type: 'uint256' }] },
  { type: 'event', name: 'NFTIssued', anonymous: false, inputs: [{ indexed: true, name: 'tokenId', type: 'uint256' }] },
  { type: 'error', name: 'InvalidParameters', inputs: [] },
  { type: 'error', name: 'InvalidState', inputs: [] },
  { type: 'error', name: 'NotAuthorized', inputs: [] },
  { type: 'error', name: 'SettlementPaused', inputs: [] },
  { type: 'error', name: 'JobNotFound', inputs: [] }
] as const
