# Private Fleet and dedicated Mac setup

<!-- Generated by scripts/docs/current-release.mjs from the companion edition map. -->

Public companion: **AGIJobManager {{VERSION}}**. Private editions: **Fleet {{FLEET}}, Agent {{AGENT}}, Node {{NODE}}**. These private applications are delivered separately; cloning this repository does not install them.

## Choose the machine and role

| Machine or service | Role | Start page in the private download |
| --- | --- | --- |
| Dedicated M1/M2 Mac mini | AGI Agent creates deliverables | Agent `START_HERE.html` |
| Dedicated M1 MacBook Pro or another Mac | AGI Node evaluates actual delivered work | Node `START_HERE.html` |
| Additional dedicated services | Employer, Evidence, Moderator and Recovery | Fleet `START_HERE.html` |

Keep signing and compute in separate Standard macOS accounts. On the Agent Mac, the existing account names `agiagentv0` and `agiagentcomputev0` can be retained. One wallet has one active signing writer and its original journal. Two Macs owned by one controller do not establish independent validation; exclude the Node's related Agent from its reviews.

Open the downloaded `START_HERE.html`, choose a role, and follow its setup and connection rehearsal. The private runtime requires its own Node.js version, currently 24.19+ within 24.x. The public repository's Node requirement applies to public build/deployment tooling.

## Upgrade without losing state

1. Stop intake and preserve a verified backup of every existing data directory and encrypted vault.
2. Reconcile pending transactions and old paid obligations. Keep claims, refunds, recovery policies, capacity reservations and cumulative spending.
3. Extract the new application separately, verify its manifest and point its launcher at the original data directory. Do not overwrite it with old application code.
4. Enroll freshly signed schema 6 participant / schema 7 employer `operator-budget` policies. Keep an existing review policy for recovery; the Node can also enroll its new review-spending budget.
5. Start observation, test the exact compute connection and supported delivery/review path, then activate the bounded commissioned scope.

The new-work workflow has no retainer funding or activation. Employer funding does not require a review-escrow policy. Existing escrow credits and refunds remain recoverable.

## Supported computer work and remaining commissioning

The supplied adapter uses public inputs and an isolated Docker desktop/browser. It binds the actual creator/reviewer model, required tools, image IDs and policy. General specifications and native file outputs are supported within those tools. Signed-in host applications, private-account adapters and automatic dependency orchestration are not implemented.

The current OpenClaw profile pin is 2026.9.5; it is a reproducible baseline, not a claim that this is the newest available OpenClaw release. Review [current computer-use capabilities](COMPUTER_USE_CURRENT.md), then commission any changed model, provider, application or tool configuration before admitting its jobs. An account subscription alone does not demonstrate API/CLI access, capacity or an available billing path.

Record actual provider costs, outcomes, false approvals/rejections, deadlines, recovery and human exception time. Local tests and historical simulations do not prove these on physical Macs. Each private package includes the detailed commissioning and rollback guides.
